# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Character customization - Base03 Blue
[character]
success_symbol = '[➜](bold #268bd2)'  # Solarized Blue
error_symbol = '[✘](bold #dc322f)'    # Solarized Red

# Kubernetes configuration
[kubernetes]
format = '[⛵ $context \($namespace\) ]($style)'
style = 'bold #cb4b16'  # Solarized Orange
disabled = false
detect_files = []
detect_extensions = []

# AWS Configuration
[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold #b58900'  # Solarized Yellow
symbol = '️⚡️'

# Git configuration
[git_branch]
format = 'on [$symbol$branch]($style) '
style = 'bold #6c71c4'  # Solarized Violet

[git_status]
format = '[\[$all_status$ahead_behind\]]($style) '
style = 'bold #dc322f'  # Solarized Red

# Disable package module
[package]
disabled = true

# Directory
[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold #2aa198"  # Solarized Cyan
format = '[📁 $path ]($style)'

[gcloud]
disabled = true